version: "3"
services:
  node:
    image: node
    volumes:
      - "~walfud/Project/ContactSync:/ContactSync"
    ports: 
      - "51955:51955"
  mongo:
    image: mongo
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 1G
    ports: 
      - "27017:27017"