version: "3"
services:

  node:
    image: node
    container_name: contactsync
    env_file: .env
    working_dir: /ContactSync
    command: npm start
    volumes:
      - .:/ContactSync
    ports:
      - "51955:3000"
    expose:
      - "3000"
    networks:
      static:
        ipv4_address: 192.168.100.120


networks:
  static:
    external: true
